# kodi default variables

# Enable custom APT repositories of Ondřej Surý, Debian and Ubuntu PHP package
# maintainer. You can enable these repositories to install PHP 7.0 on Debian
# Jessie. See :ref:`php__ref_sury` for more details.
kodi__ppa: '{{ (ansible_local.kodi.ppa
                if (ansible_local|d() and ansible_local.kodi|d() and
                    ansible_local.kodi.ppa|d())
                else False) | bool }}'

# The OpenPGP key used to sign Ondřej Surý APT repository, dependent on the current
# OS distribution.
kodi__ppa_apt_key_id: '189701DA570C56B9488EF60A6D975C4791E7EE5E'

# APT repository URL to Ondřej Surý repository, dependent on the current OS
# distribution.
kodi__ppa_apt_repo: '{{ kodi__ppa_apt_repo_map[ansible_distribution] }}'

# YAML dictionary map of APT repository URLs, dependent on the OS distribution.
kodi__ppa_apt_repo_map:
  'Debian': 'deb http://ppa.launchpad.net/team-xbmc/ppa/ubuntu {{ ansible_distribution_release }} main'
  'Ubuntu': 'ppa:team-xbmc/ppa'
