transmission__ferm__dependent_rules:

  - type: 'accept'
    protocol: [ 'tcp', 'udp']
    dport: [ 9091, 51413, '49152:65535' ]
    saddr: [ '192.168.0.0/24' ]
    accept_any: True
    weight: '40'
    by_role: 'transmission'
    name: 'transmission'
