---
- name: Upgrade with apt (update cache)
  apt: upgrade=dist update_cache=yes dpkg_options='force-confold,force-confdef'
  register: apt_result
  ignore_errors: True

- name: Upgrade with apt
  apt: upgrade=dist update_cache=no dpkg_options='force-confold,force-confdef'
  when: "'Could not fetch updated apt files' in apt_result.stderr"

- name: Update MOTD
  shell: run-parts --lsbsysinit /etc/update-motd.d 1>/dev/null 2>&1
  async: 45
  poll: 0

- name: Check if reboot is required
  stat: path=/var/run/reboot-required
  register: reboot_required

- name: Schedule a reboot
  shell: /usr/bin/nohup /sbin/shutdown -r 03:00 &
  async: 45
  poll: 0
  when: reboot_required.stat.exists == True
  # bug in 1.7: https://github.com/ansible/ansible/pull/7621
