---
- name: Webserver tasks
  hosts: webservers
  become: true
  become_method: sudo

  pre_tasks:
    - name: Check that dhparam file exists
      stat:
        path: /etc/nginx/dhparam.pem
      register: dhparam_result

    - name: Create the dhparam file, if it does not exist already
      command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
      when: dhparam_result.stat.exists == False

  roles:
    # dependencies
    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ nginx__apt_preferences__dependent_list }}'

    # ferm
    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'

    # actual roles
    - role: debops.nginx
    - role: parking
