---
- name: Webserver tasks
  hosts: webservers
  become: true
  become_method: sudo

  pre_tasks:
    - name: Install python3-mysqldb which is required for MySQL
      apt:
        name: ['python3-mysqldb']
        state: present

    - name: Check that dhparam file exists
      stat:
        path: /etc/nginx/dhparam.pem
      register: dhparam_result

    - name: Create the dhparam file, if it does not exist already
      command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
      when: dhparam_result.stat.exists == False

  roles:
    # nginx, mariadb_server, php
    - role: debops.keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::php' ]
      keyring__dependent_apt_keys:
        - '{{ php__keyring__dependent_apt_keys }}'

    # pre-requisites
    - role: debops.php/env
      tags: [ 'role::php' ]

    # dependencies
    - role: debops.apt_preferences
      tags: [ 'role::php' ]
      apt_preferences__dependent_list:
        - '{{ nginx__apt_preferences__dependent_list }}'
        - '{{ php__apt_preferences__dependent_list }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'
        - '{{ mariadb_server__ferm__dependent_rules }}'

    - role: debops.tcpwrappers
      tcpwrappers__dependent__allow:
        - '{{ mariadb_server__tcpwrappers__dependent_allow }}'

    - role: debops.logrotate
      tags: [ 'role::logrotate' ]
      logrotate__dependent_config:
        - '{{ php__logrotate__dependent_config }}'

    # actual roles
    - role: debops.nginx
    - role: debops.php
      tags: [ 'role::php' ]
    - role: debops.mariadb_server
    - role: parking
